#!/bin/bash
bundle exec rake cleanup bootstrap parallel_spec documentation:dashboard
bundle exec rspec spec/phase2/feature_coverage_report.rb --format MatrixFormatter::Formatters::HTMLFormatter --out reports/api_coverage.html
