#!/bin/bash
export GOPATH=`pwd`/go
CHALLENGES_DIR=$(dirname $1)
export SDK_PROVIDER=${RAX_AUTH_URL}/v2.0/tokens
# export SDK_PROVIDER=rackspace-us
export SDK_USERNAME=$RAX_USERNAME
export SDK_API_KEY=$RAX_API_KEY
export SDK_PASSWORD=none
# go run $1 $CHALLENGES_DIR/libargs.go
go run $1
